export enum SettingsEnum {
  REC_OPEN = 'REC_OPEN',
  REC_CLOSE = 'REC_CLOSE',
  REC_MID_ANNOUNCE = 'REC_MID_ANNOUNCE',
  REC_INTERVIEW_START = 'REC_INTERVIEW_START',
  REC_INTERVIEW_END = 'REC_INTERVIEW_END',
  REC_FINAL_ANNOUNCE = 'REC_FINAL_ANNOUNCE',
}
