name: Build and Deploy

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Create env directory
        run: mkdir -p env

      - name: Create .env.prod file
        run: echo "${{ secrets.ENV_PROD }}" > env/.env.prod

      - name: Get current time
        run: echo "CURRENT_TIME=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:${{ env.CURRENT_TIME }},
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64 #,linux/arm64

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      #- name: Deploy to Production Server
      #  if: github.ref == 'refs/heads/main'
      #  uses: appleboy/ssh-action@v0.1.5
      #  with:
      #    host: ${{ secrets.SERVER_HOST }}
      #    username: ${{ secrets.SERVER_USERNAME }}
      #    key: ${{ secrets.SERVER_SSH_KEY }}
      #    script: |
      #      cd ~/dasom
      #      docker-compose pull
      #      docker-compose up -d
      #      docker image prune -f

      - name: Deploy to Test Server
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/dasom
            docker-compose pull
            docker-compose up -d
            docker image prune -f
